image: java:8-jdk

stages:
  - build
  - test
  - deploy

before_script:
#  - echo `pwd` # debug
#  - echo "$CI_BUILD_NAME, $CI_BUILD_REF_NAME $CI_BUILD_STAGE" # debug
  - export GRADLE_USER_HOME=`pwd`/.gradle

cache:
  paths:
    - .gradle/wrapper
    - .gradle/caches

build:
  stage: build
  artifacts:
      expire_in: 1 week
      paths:
        - artifacts/de.itemis.mps.generator.editors
  script:
    - ./gradlew build

release:
  stage: deploy
  when: manual
  only:
    - master
  script:
    - ./gradlew githubRelease
