name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4.1.1
    - name: Set up JDK 11
      uses: actions/setup-java@v4.0.0
      with:
        java-version: 11
        distribution: 'adopt'
    - name: Build with Gradle
      run: ./gradlew build
