name: Modelix URL

on: [pull_request_target]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: coolya/action-pr-link@v0.1
    with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        modelix-url: "http://modelix.q60.de"  
